---
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codech3ry/spring-cloud-config-wa-tolls
          search-paths:
            - 'station*'
#          username:
#          password:
